export const GET_ALL_SERVICE_PROVIDER = "GET_ALL_SERVICE_PROVIDER";
export const GET_SINGLE_SERVICE_PROVIDER = "GET_SINGLE_SERVICE_PROVIDER";
export const DELETE_SINGLE_SERVICE_PROVIDER = "DELETE_SINGLE_SERVICE_PROVIDER";
export const GET_ALL_SERVICE_TYPE = "GET_ALL_SERVICE_TYPE";
export const OPEN_DIALOG_SERVICE_TYPE = "OPEN_DIALOG_SERVICE_TYPE";
export const CLOSE_DIALOG_SERVICE_TYPE = "CLOSE_DIALOG_SERVICE_TYPE";
export const GET_SERVICE_CATEGORY = "GET_SERVICE_CATEGORY";
export const ADD_SERVICE_CATEGORY = "CREATE_SERVICE_CATEGORY";
export const ADD_SERVICE_TYPE = "CREATE_SERVICE_TYPE";
export const APPROVED_SERVICE_PROVIDER = "APPROVED_SERVICE_PROVIDER";
export const OPEN_DIALOG_SERVICE_CATEGORY = "OPEN_DIALOG_SERVICE_CATEGORY";
export const CLOSE_DIALOG_SERVICE_CATEGORY = "CLOSE_DIALOG_SERVICE_CATEGORY";

