export const GET_ALL_SERVICE_PROVIDER = "GET_ALL_SERVICE_PROVIDER";
export const GET_ALL_SERVICE_PROVIDER_SUCCESS = "GET_ALL_SERVICE_PROVIDER_SUCCESS";
export const GET_ALL_SERVICE_PROVIDER_ERROR = "GET_ALL_SERVICE_PROVIDER_ERROR";

export const GET_SINGLE_SERVICE_PROVIDER = "GET_SINGLE_SERVICE_PROVIDER";
export const GET_SINGLE_SERVICE_PROVIDER_SUCCESS = "GET_SINGLE_SERVICE_PROVIDER_SUCCESS";
export const GET_SINGLE_SERVICE_PROVIDER_ERROR = "GET_SINGLE_SERVICE_PROVIDER_ERROR";

export const DELETE_SINGLE_SERVICE_PROVIDER = "DELETE_SINGLE_SERVICE_PROVIDER";
export const DELETE_SINGLE_SERVICE_PROVIDER_SUCCESS = "DELETE_SINGLE_SERVICE_PROVIDER_SUCCESS";
export const DELETE_SINGLE_SERVICE_PROVIDER_ERROR = "DELETE_SINGLE_SERVICE_PROVIDER_ERROR";

export const GET_ALL_SERVICE_TYPE = "GET_ALL_SERVICE_TYPE";
export const GET_ALL_SERVICE_TYPE_SUCCESS = "GET_ALL_SERVICE_TYPE_SUCCESS";
export const GET_ALL_SERVICE_TYPE_ERROR = "GET_ALL_SERVICE_TYPE_ERROR";

export const OPEN_DIALOG_SERVICE_TYPE = "OPEN_DIALOG_SERVICE_TYPE";
export const OPEN_EDIT_DIALOG_SERVICE_TYPE = "OPEN_EDIT_DIALOG_SERVICE_TYPE";
export const CLOSE_DIALOG_SERVICE_TYPE = "CLOSE_DIALOG_SERVICE_TYPE";
export const CLOSE_EDIT_DIALOG_SERVICE_TYPE = "CLOSE_EDIT_DIALOG_SERVICE_TYPE";

export const GET_SERVICE_CATEGORY = "GET_SERVICE_CATEGORY";
export const GET_SERVICE_CATEGORY_SUCCESS = "GET_SERVICE_CATEGORY_SUCCESS";
export const GET_SERVICE_CATEGORY_ERROR = "GET_SERVICE_CATEGORY_ERROR";

export const ADD_SERVICE_CATEGORY = "CREATE_SERVICE_CATEGORY";
export const ADD_SERVICE_CATEGORY_SUCCESS = "CREATE_SERVICE_CATEGORY_SUCCESS";
export const ADD_SERVICE_CATEGORY_ERROR = "CREATE_SERVICE_CATEGORY_ERROR";

export const EDIT_SERVICE_TYPE = "EDIT_SERVICE_TYPE";
export const EDIT_SERVICE_TYPE_SUCCESS = "EDIT_SERVICE_TYPE_SUCCESS";
export const EDIT_SERVICE_TYPE_ERROR = "EDIT_SERVICE_TYPE_ERROR";

export const DELETE_SERVICE_TYPE = "DELETE_SERVICE_TYPE";
export const DELETE_SERVICE_TYPE_SUCCESS = "DELETE_SERVICE_TYPE_SUCCESS";
export const DELETE_SERVICE_TYPE_ERROR = "DELETE_SERVICE_TYPE_ERROR";

export const APPROVED_SERVICE_PROVIDER = "APPROVED_SERVICE_PROVIDER";
export const APPROVED_SERVICE_PROVIDER_SUCCESS = "APPROVED_SERVICE_PROVIDER_SUCCESS";
export const APPROVED_SERVICE_PROVIDER_ERROR = "APPROVED_SERVICE_PROVIDER_ERROR";

export const OPEN_DIALOG_SERVICE_CATEGORY = "OPEN_DIALOG_SERVICE_CATEGORY";
export const CLOSE_DIALOG_SERVICE_CATEGORY = "CLOSE_DIALOG_SERVICE_CATEGORY";

