export const GET_ALL_TENANT = "GET_ALL_TENANT";
export const GET_ALL_TENANT_SUCCESS = "GET_ALL_TENANT_SUCCESS";
export const GET_ALL_TENANT_ERROR = "GET_ALL_TENANT_ERROR";

export const GET_SINGLE_TENANT = "GET_SINGLE_TENANT";
export const GET_SINGLE_TENANT_SUCCESS = "GET_SINGLE_TENANT_SUCCESS";
export const GET_SINGLE_TENANT_ERROR = "GET_SINGLE_TENANT_ERROR";

export const DELETE_SINGLE_TENANT = "DELETE_SINGLE_TENANT";
export const DELETE_SINGLE_TENANT_SUCCESS = "DELETE_SINGLE_TENANT_SUCCESS";
export const DELETE_SINGLE_TENANT_ERROR = "DELETE_SINGLE_TENANT_ERROR";

export const GET_TENANT_PROPERTY = "GET_TENANT_PROPERTY";
export const GET_TENANT_PROPERTY_ERROR = "GET_TENANT_PROPERTY_ERROR";
export const GET_TENANT_PROPERTY_SUCCESS = "GET_TENANT_PROPERTY_SUCCESS";
