export const GET_ALL_TENANT = "GET_ALL_TENANT";
export const GET_SINGLE_TENANT = "GET_SINGLE_TENANT";
export const DELETE_SINGLE_TENANT = "DELETE_SINGLE_TENANT";
export const GET_TENANT_PROPERTY = "GET_TENANT_PROPERTY"
