export const GET_ALL_AGENT = "GET_ALL_AGENT";
export const GET_ALL_AGENT_SUCCESS = "GET_ALL_AGENT_SUCCESS";
export const GET_ALL_AGENT_ERROR = "GET_ALL_AGENT_ERROR";

export const GET_SINGLE_AGENT = "GET_SINGLE_AGENT";
export const GET_SINGLE_AGENT_SUCCESS = "GET_SINGLE_AGENT_SUCCESS";
export const GET_SINGLE_AGENT_ERROR = "GET_SINGLE_AGENT_ERROR";

export const DELETE_SINGLE_AGENT = "DELETE_SINGLE_AGENT";
export const DELETE_SINGLE_AGENT_SUCCESS = "DELETE_SINGLE_AGENT_SUCCESS";
export const DELETE_SINGLE_AGENT_ERROR = "DELETE_SINGLE_AGENT_ERROR";

