export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES";
export const GET_ALL_PROPERTIES_SUCCESS = "GET_ALL_PROPERTIES_SUCCESS";
export const GET_ALL_PROPERTIES_ERROR = "GET_ALL_PROPERTIES_ERROR";

export const VIEW_SINGLE_PROPERTY = "VIEW_SINGLE_PROPERTY";
export const VIEW_SINGLE_PROPERTY_SUCCESS = "VIEW_SINGLE_PROPERTY_SUCCESS";
export const VIEW_SINGLE_PROPERTY_ERROR = "VIEW_SINGLE_PROPERTY_ERROR";

export const APPROVE_PROPERTIES = 'APPROVE_PROPERTIES';
export const APPROVE_PROPERTIES_SUCCESS = 'APPROVE_PROPERTIES_SUCCESS';
export const APPROVE_PROPERTIES_ERROR = 'APPROVE_PROPERTIES_ERROR';
