export const GET_WALK_VIDEO_PLANS = "GET_WALK_VIDEO_PLANS";
export const GET_WALK_VIDEO_PLANS_SUCCESS = "GET_WALK_VIDEO_PLANS_SUCCESS";
export const GET_WALK_VIDEO_PLANS_ERROR = "GET_WALK_VIDEO_PLANS_ERROR";

export const GET_ALL_APARTMENT_TYPES = "GET_ALL_APARTMENT_TYPES";
export const GET_ALL_APARTMENT_TYPES_SUCCESS = "GET_ALL_APARTMENT_TYPES_SUCCESS";
export const GET_ALL_APARTMENT_TYPES_ERROR = "GET_ALL_APARTMENT_TYPES_ERROR";

export const UPDATE_WALK_VIDEO_FEE = "UPDATE_WALK_VIDEO_FEE";
export const UPDATE_WALK_VIDEO_FEE_SUCCESS = "UPDATE_WALK_VIDEO_FEE_SUCCESS";
export const UPDATE_WALK_VIDEO_FEE_ERROR = "UPDATE_WALK_VIDEO_FEE_ERROR";

export const OPEN_WALK_UPLOAD_DIALOG = "OPEN_WALK_UPLOAD_DIALOG";
export const CLOSE_WALK_UPLOAD_DIALOG = "CLOSE_WALK_UPLOAD_DIALOG";

export const UPLOAD_VIDEO = "UPLOAD_VIDEO";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_ERROR = "UPLOAD_VIDEO_ERROR";