export const GET_WALK_VIDEO_PLANS = "GET_WALK_VIDEO_PLANS";
export const GET_WALK_VIDEO_PLANS_SUCCESS = "GET_WALK_VIDEO_PLANS_SUCCESS";
export const GET_WALK_VIDEO_PLANS_ERROR = "GET_WALK_VIDEO_PLANS_ERROR";

export const GET_ALL_APARTMENT_TYPES = "GET_ALL_APARTMENT_TYPES";
export const GET_ALL_APARTMENT_TYPES_SUCCESS = "GET_ALL_APARTMENT_TYPES_SUCCESS";
export const GET_ALL_APARTMENT_TYPES_ERROR = "GET_ALL_APARTMENT_TYPES_ERROR";

export const UPDATE_WALK_VIDEO_FEE = "UPDATE_WALK_VIDEO_FEE";
export const UPDATE_WALK_VIDEO_FEE_SUCCESS = "UPDATE_WALK_VIDEO_FEE_SUCCESS";
export const UPDATE_WALK_VIDEO_FEE_ERROR = "UPDATE_WALK_VIDEO_FEE_ERROR";