export const GET_PMA_FEES = "GET_PMA_FEES";
export const GET_PMA_FEES_SUCCESS = "GET_PMA_FEES_SUCCESS";
export const GET_PMA_FEES_ERROR = "GET_PMA_FEES_ERROR";

export const UPDATE_PMA_FEES = "UPDATE_PMA_FEES";
export const UPDATE_PMA_FEES_SUCCESS = "UPDATE_PMA_FEES_SUCCESS";
export const UPDATE_PMA_FEES_ERROR = "UPDATE_PMA_FEES_ERROR";