export const GET_ALL_PROPERTYOWERS = "GET_ALL_PROPERTYOWERS";
export const GET_ALL_PROPERTYOWERS_SUCCESS = "GET_ALL_PROPERTYOWERS_SUCCESS";
export const GET_ALL_PROPERTYOWERS_ERROR = "GET_ALL_PROPERTYOWERS_ERROR";

export const GET_SINGLE_PROPERTYOWER = "GET_SINGLE_PROPERTYOWER";
export const GET_SINGLE_PROPERTYOWER_SUCCESS = "GET_SINGLE_PROPERTYOWER_SUCCESS";
export const GET_SINGLE_PROPERTYOWER_ERROR = "GET_SINGLE_PROPERTYOWER_ERROR";

export const DELETE_SINGLE_PROPERTYOWER = "DELETE_SINGLE_PROPERTYOWER";
export const DELETE_SINGLE_PROPERTYOWER_SUCCESS = "DELETE_SINGLE_PROPERTYOWER_SUCCESS";
export const DELETE_SINGLE_PROPERTYOWER_ERROR = "DELETE_SINGLE_PROPERTYOWER_ERROR";
