export const GET_ALL_PROPERTYOWERS = "GET_ALL_PROPERTYOWERS";
export const GET_SINGLE_PROPERTYOWER = "GET_SINGLE_PROPERTYOWER";
export const DELETE_SINGLE_PROPERTYOWER = "DELETE_SINGLE_PROPERTYOWER";
