export const GET_ALL_ADMIN = "GET_ALL_ADMIN";
export const GET_ALL_ADMIN_SUCCESS = "GET_ALL_ADMIN_SUCCESS";
export const GET_ALL_ADMIN_ERROR = "GET_ALL_ADMIN_ERROR";

export const OPEN_ADMIN_DIALOG = "OPEN_ADMIN_DIALOG";
export const CLOSE_ADMIN_DIALOG = "CLOSE_ADMIN_DIALOG";

export const ADD_NEW_ADMIN = "ADD_NEW_ADMIN";
export const ADD_NEW_ADMIN_SUCCESS = "ADD_NEW_ADMIN_SUCCESS";
export const ADD_NEW_ADMIN_ERROR = "ADD_NEW_ADMIN_ERROR";

export const DELETE_SINGLE_ADMIN = "DELETE_SINGLE_ADMIN";
export const DELETE_SINGLE_ADMIN_SUCCESS= "DELETE_SINGLE_ADMIN_SUCCESS";
export const DELETE_SINGLE_ADMIN_ERROR = "DELETE_SINGLE_ADMIN_ERROR";