export const GET_ALL_ADMIN = 'GET_ALL_ADMIN';
export const OPEN_ADMIN_DIALOG = 'OPEN_ADMIN_DIALOG';
export const CLOSE_ADMIN_DIALOG = 'CLOSE_ADMIN_DIALOG';
export const  ADD_NEW_ADMIN = 'ADD_NEW_ADMIN';